name: hyde
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_remix: ^0.0.3
  flutter_svg: ^1.1.0
  freezed_annotation: ^2.0.3
  get: ^4.6.5
  readmore: ^2.1.0
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/svgs/
    - assets/data/
