final List<Map<String, dynamic>> anilist = [
  {
    'id': '0',
    'title': '스파이 패밀리',
    'types': ['2020', '만화'],
    'image': "https://bit.ly/3zn69ij",
    'status': '감상중',
  },
  {
    'id': '1',
    'title': '바이올렛 에버가든',
    'types': ['2021', '영화'],
    'image': "https://bit.ly/33AxUGh",
    'completedAt': DateTime(2021, 12),
    'status': '감상중',
  },
  {
    'id': '2',
    'title': '3월의 라이온',
    'types': ['2016', 'TV'],
    'image': "https://bit.ly/3wWjMSv",
    'completedAt': DateTime(2021, 10),
    'status': '감상중',
  },
  {
    'id': '3',
    'title': '호리미야',
    'types': ['2021', 'TV'],
    'image': "https://bit.ly/3GRa7AS",
    'status': '감상전',
  },
  {
    'id': '4',
    'title': '무직전생',
    'types': ['2021', 'TV'],
    'image': "https://bit.ly/3DVOf4O",
    'status': '감상전',
  },
  {
    'id': '6',
    'title': '빙과',
    'types': ['2014', 'TV'],
    'image': "https://bit.ly/3IR3DTC",
    'status': '감상전',
  },
  {
    'id': '7',
    'title': '흑의 계약자',
    'types': ['2014', 'TV'],
    'image': "https://bit.ly/3yw0ofI",
    'completedAt': DateTime(2021, 10),
    'status': '감상전',
  },
  {
    'id': '8',
    'title': '사쿠라다 리셋',
    'types': ['2014', 'TV'],
    'image': "https://bit.ly/3m6bCTc",
    'status': '감상전',
  },
  {
    'id': '9',
    'title': '슈타인즈 게이트',
    'types': ['2014', 'TV'],
    'image': "https://bit.ly/3pXWo3x",
    'status': '감상전',
  },
];
